// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// GroupMCMCLN
List GroupMCMCLN(arma::vec Y, arma::vec I, arma::vec Doses, arma::vec Groups, double meanmu, double meanslope, arma::vec MeanInts, arma::vec MeanSlopes, int B, double T1);
RcppExport SEXP SubTite_GroupMCMCLN(SEXP YSEXP, SEXP ISEXP, SEXP DosesSEXP, SEXP GroupsSEXP, SEXP meanmuSEXP, SEXP meanslopeSEXP, SEXP MeanIntsSEXP, SEXP MeanSlopesSEXP, SEXP BSEXP, SEXP T1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type I(ISEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Doses(DosesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Groups(GroupsSEXP);
    Rcpp::traits::input_parameter< double >::type meanmu(meanmuSEXP);
    Rcpp::traits::input_parameter< double >::type meanslope(meanslopeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type MeanInts(MeanIntsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type MeanSlopes(MeanSlopesSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type T1(T1SEXP);
    rcpp_result_gen = Rcpp::wrap(GroupMCMCLN(Y, I, Doses, Groups, meanmu, meanslope, MeanInts, MeanSlopes, B, T1));
    return rcpp_result_gen;
END_RCPP
}
// SimTrial1
List SimTrial1(int nSims, int Nmax, double T1, arma::vec Target, arma::vec Dose, arma::vec DoseStart, double TGroup, arma::vec Upper, double Accrue, arma::vec groupprob, int Family, arma::mat Param1, arma::mat Param2, double meanmu, double meanslope, arma::vec MeanInts, arma::vec MeanSlopes);
RcppExport SEXP SubTite_SimTrial1(SEXP nSimsSEXP, SEXP NmaxSEXP, SEXP T1SEXP, SEXP TargetSEXP, SEXP DoseSEXP, SEXP DoseStartSEXP, SEXP TGroupSEXP, SEXP UpperSEXP, SEXP AccrueSEXP, SEXP groupprobSEXP, SEXP FamilySEXP, SEXP Param1SEXP, SEXP Param2SEXP, SEXP meanmuSEXP, SEXP meanslopeSEXP, SEXP MeanIntsSEXP, SEXP MeanSlopesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nSims(nSimsSEXP);
    Rcpp::traits::input_parameter< int >::type Nmax(NmaxSEXP);
    Rcpp::traits::input_parameter< double >::type T1(T1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Target(TargetSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Dose(DoseSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type DoseStart(DoseStartSEXP);
    Rcpp::traits::input_parameter< double >::type TGroup(TGroupSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Upper(UpperSEXP);
    Rcpp::traits::input_parameter< double >::type Accrue(AccrueSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type groupprob(groupprobSEXP);
    Rcpp::traits::input_parameter< int >::type Family(FamilySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Param1(Param1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Param2(Param2SEXP);
    Rcpp::traits::input_parameter< double >::type meanmu(meanmuSEXP);
    Rcpp::traits::input_parameter< double >::type meanslope(meanslopeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type MeanInts(MeanIntsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type MeanSlopes(MeanSlopesSEXP);
    rcpp_result_gen = Rcpp::wrap(SimTrial1(nSims, Nmax, T1, Target, Dose, DoseStart, TGroup, Upper, Accrue, groupprob, Family, Param1, Param2, meanmu, meanslope, MeanInts, MeanSlopes));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"SubTite_GroupMCMCLN", (DL_FUNC) &SubTite_GroupMCMCLN, 10},
    {"SubTite_SimTrial1", (DL_FUNC) &SubTite_SimTrial1, 17},
    {NULL, NULL, 0}
};

RcppExport void R_init_SubTite(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
