# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GroupMCMCLN <- function(Y, I, Doses, Groups, meanmu, meanslope, MeanInts, MeanSlopes, B, T1) {
    .Call('SubTite_GroupMCMCLN', PACKAGE = 'SubTite', Y, I, Doses, Groups, meanmu, meanslope, MeanInts, MeanSlopes, B, T1)
}

SimTrial1 <- function(nSims, Nmax, T1, Target, Dose, DoseStart, TGroup, Upper, Accrue, groupprob, Family, Param1, Param2, meanmu, meanslope, MeanInts, MeanSlopes) {
    .Call('SubTite_SimTrial1', PACKAGE = 'SubTite', nSims, Nmax, T1, Target, Dose, DoseStart, TGroup, Upper, Accrue, groupprob, Family, Param1, Param2, meanmu, meanslope, MeanInts, MeanSlopes)
}

